export enum UserRole {
	ADMIN = 'ADMIN',
	SENIOR_VOLUNTEER = 'SENIOR_VOLUNTEER',
	VOLUNTEER = 'VOLUNTEER',
	GUARDIAN = 'GUARDIAN'
}

export const STAFF_ROLES = [UserRole.VOLUNTEER, UserRole.SENIOR_VOLUNTEER, UserRole.ADMIN];
