events {
	worker_connections 4096;
}

http {
	include /etc/nginx/mime.types;

	server {
		listen 80;
		root /usr/share/nginx/html;
		index index.html;

		location / {
			try_files $uri $uri/ /index.html;
		}

		location ~* \.(js|mjs|css|png|jpg|jpeg|svg|ico|json)$ {
			try_files $uri =404;
			expires 1y;
			add_header Cache-Control "public";
		}
	}
}
