export const GUARDIAN_DEFAULT_POSITION = 'Опекун';

export const GUARDIANSHIP_BILLING_PERIOD_MONTHS = 1;

export const GUARDIAN_PENDING_PAYMENT_EXPIRE_MS = 1000 * 60 * 10;
export const GUARDIAN_TELEGRAM_REMINDER_DELAY_MS = 24 * 60 * 60 * 1000;
