import z from 'zod';

export const envSchema = z.object({
	DATABASE_URL: z.url(),
	SECRET: z.string().min(8),
	NODE_ENV: z.enum(['development', 'production', 'test']).default('development'),
	ALLOWED_ORIGINS: z.string().default('http://localhost:5173,http://localhost:3001'),
	ADMIN_EMAIL: z.email(),
	ADMIN_PASSWORD: z.string().min(8),
	ADMIN_TELEGRAM: z.string().startsWith('@'),
	BASE_URL: z.url(),
	APP_BASE_URL: z.url(),
	ADMIN_BASE_URL: z.url(),
	SMTP_PASSWORD: z.string(),
	SMTP_HOST: z.string(),
	SMTP_PORT: z.coerce.number(),
	SMTP_EMAIL: z.email(),
	SMTP_NAME: z.string(),
	HEALTH_DISK_THRESHOLD_PERCENT: z.coerce.number(),
	HEALTH_MEMORY_THRESHOLD_BYTES: z.coerce.number(),
	REDIS_URL: z.string(),
	REDIS_TTL_SECONDS: z.coerce.number().positive().default(60),
	REDIS_KEY_PREFIX: z.string(),
	REDIS_HASH_SALT: z.string(),
	S3_REGION: z.string(),
	S3_ENDPOINT: z.url(),
	S3_ACCESS_TOKEN: z.string(),
	S3_PUBLIC_ENDPOINT: z.string(),
	S3_ACCESS_SECRET_TOKEN: z.string(),
	S3_BUCKET: z.string(),
	QUEUE_REDIS_URL: z.string(),
	TELEGRAM_ADMIN_USERNAME: z.string(),
	TELEGRAM_BOT_USERNAME: z.string().default('pif_shelter_bot'),
	TELEGRAM_BOT_TOKEN: z.string().optional(),
	TELEGRAM_CHAT_REPORT_TOPIC: z.coerce.number().optional(),
	TELEGRAM_CHAT_ID: z.coerce.number().optional(),
	BOT_HELP_CONTACTS: z.string().optional(),
	BOT_HELP_ADDRESS: z.string().optional(),
	BOT_HELP_VISITING_RULES: z.string().optional(),
	BOT_HELP_SITE_URL: z.string().optional()
});

export type Env = z.infer<typeof envSchema>;
