export const FinanceErrorCodes = {
	DONATION_AMOUNT_INVALID: 'DONATION_AMOUNT_INVALID',
	MANUAL_EXPENSE_RECEIPT_REQUIRED: 'MANUAL_EXPENSE_RECEIPT_REQUIRED',
	MANUAL_EXPENSE_NOT_FOUND: 'MANUAL_EXPENSE_NOT_FOUND',
	LEDGER_ENTRY_NOT_FOUND: 'LEDGER_ENTRY_NOT_FOUND',
	PAYMENT_WEBHOOK_VALIDATION: 'PAYMENT_WEBHOOK_VALIDATION',
	PAYMENT_WEBHOOK_NOT_ROUTED: 'PAYMENT_WEBHOOK_NOT_ROUTED'
} as const;

export type FinanceErrorCode = (typeof FinanceErrorCodes)[keyof typeof FinanceErrorCodes];
