import { DONATION_MAX_AMOUNT_KOPECKS, DONATION_MIN_AMOUNT_KOPECKS } from '@pif/shared';

export const DONATION_PRESET_AMOUNTS_KOPECKS = [100_00, 300_00, 500_00, 1_000_00, 5_000_00] as const;

export const DONATION_FEED_PREVIEW_LIMIT = 6;

export const DEFAULT_DONATION_AMOUNT_KOPECKS = 500_00;

export { DONATION_MAX_AMOUNT_KOPECKS, DONATION_MIN_AMOUNT_KOPECKS };
